### PR TITLE
Add hot-reload capability using VNODE dispatch source

### PR DESCRIPTION
**Pull request by igor-makarov**
This PR is intended for Simulator-based development but uses only public API.

Whenever a file's source path is discovered, a `FileWatcher` object is created and attached to it.
It uses a DispatchSource of type VNODE to receive a callback each time the file is written to.

Whenever a watcher is available, `LayoutLoading.reloadLayout()` gets hooked up to it and is called on file save.
This addresses [#51](https://github.com/schibsted/layout/issues/51)

### CODE REVIEW

**Comment by nicklockwood** [comment]
@igor-makarov this looks great, thanks!

**Comment by nicklockwood** [comment]
@igor-makarov when I tested this before it seemed to work (apart from the issues I mentioned), but when I tried it again now in Xcode 9.4.1, the FileWatcher fileChanged() callback is never firing, even on the root xml file.

Is it working for you?

**Comment by flexih** [comment]
@nicklockwood Write is not fired when edit xml file in Xcode, while does in Sublime Text, weird.

**Comment by igor-makarov** [comment]
Hey, I just couldn't find the time to finish this. Sorry! 😳

**Comment by nicklockwood** [comment]
@igor-makarov no problem - I’ll look into doing it myself at some point.

**Pull request closed without merging**
